main="./app/worker/index.ts"
name = "demo-cfw-ssr"
compatibility_date = "2022-05-03"
workers_dev = true
node_compat = true

[site]
bucket = "./app/build/client"

[dev]
port = 3000

[vars]
ENVIRONMENT = "dev"
LOG_LEVEL = "debug"

kv_namespaces = [
  # DEMO_CFW_SSR_preview
  { binding = "DEMO_CFW_SSR", id = "", preview_id = "" }
]
