compatibility_date = "2023-04-08"
main = "./app/build/worker/worker.mjs"
name = "demo-cfw-ssr"
node_compat = true
workers_dev = true
[dev]
port = 3000
[[env.dev.routes]]
custom_domain = true
pattern = "demos-dev.shortpoet.com"
[env.dev.vars]
API_VERSION = "v6"
ENVIRONMENT = "dev"
LOG_LEVEL = "debug"
SSR_BASE_PATHS = "about,api-data,index,star-wars"
VITE_API_URL = "http://localhost:3000"
VITE_APP_NAME = "demo-cfw-ssr"
VITE_APP_URL = "http://localhost:3000"
VITE_LOG_LEVEL = "debug"
VITE_PORT = "3000"
[site]
bucket = "./app/build/client"
