compatibility_date = "2023-02-28"
# main = "./dist/worker.js"
main = "./app/worker/index.ts"
name = "demo-cfw-ssr"
node_compat = true
workers_dev = true
# [build]
# command = "pnpm build:w"
[dev]
port = 3000
[[env.dev.kv_namespaces]]
binding = "DEMO_CFW_SSR"
id = "3740e85e3b174682964efa26066fa5c4"
preview_id = "3740e85e3b174682964efa26066fa5c4"
[[env.dev.kv_namespaces]]
binding = "DEMO_CFW_SSR_SESSIONS"
id = "a41123f53b804770b6808ef4b924f930"
preview_id = "a41123f53b804770b6808ef4b924f930"
[[env.dev.kv_namespaces]]
binding = "DEMO_CFW_SSR_USERS"
id = "ef2b919ed69a49c5bf33349b2c943fc7"
preview_id = "ef2b919ed69a49c5bf33349b2c943fc7"
[env.dev.vars]
AUTH0_DOMAIN = "shortpoet.auth0.com"
ENVIRONMENT = "dev"
LOG_LEVEL = "info"
NEXTAUTH_URL = "http://localhost:3000/api/next-auth"
[[env.prod.kv_namespaces]]
binding = "DEMO_CFW_SSR"
id = "5c6a1909d0844b4296607e021240e9f1"
preview_id = "5c6a1909d0844b4296607e021240e9f1"
[env.prod.vars]
ENVIRONMENT = "prod"
LOG_LEVEL = "error"
NEXTAUTH_URL = "http://localhost:3000/api/next-auth"
[site]
bucket = "./app/build/client"
