compatibility_date = "2023-02-28"
main = "./app/worker/index.ts"
name = "demo-cfw-ssr"
node_compat = true
workers_dev = true
[dev]
port = 3000
[env.dev.vars]
ENVIRONMENT = "dev"
LOG_LEVEL = "debug"
SSR_BASE_PATHS = "about,api-data,index,star-wars"
[site]
bucket = "./app/build/client"
