name = "demo-cfw-ssr"
compatibility_date = "2022-05-03"
main = "./app/worker/index.ts"
node_compat = true
workers_dev = true
[dev]
port = 3000
[[env.dev.vars]]
ENVIRONMENT = "dev"
LOG_LEVEL = "debug"
[[env.dev.kv_namespaces]]
binding = "DEMO_CFW_SSR"
id = "s"
preview_id = "s"
[[env.prod.vars]]
ENVIRONMENT = "prod"
LOG_LEVEL = "error"
[[env.prod.kv_namespaces]]
binding = "DEMO_CFW_SSR"
id = "s"
preview_id = "s"
[site]
bucket = "./app/build/client"
