compatibility_date = "2023-02-28"
main = "./app/worker/index.ts"
name = "demo-cfw-ssr"
node_compat = true
workers_dev = true
[dev]
port = 3000
[[env.dev.routes]]
custom_domain = true
pattern = "demos-dev.shortpoet.com"
[env.dev.vars]
API_VERSION = "v5"
ENVIRONMENT = "dev"
LOG_LEVEL = "debug"
SSR_BASE_PATHS = "about,api-data,index,star-wars"
VITE_API_URL = "https://demo-cfw-ssr-dev.shortpoet.workers.dev"
VITE_APP_NAME = "demo-cfw-ssr"
VITE_APP_URL = "https://demo-cfw-ssr-dev.shortpoet.workers.dev"
VITE_LOG_LEVEL = "info"
[site]
bucket = "./app/build/client"
