compatibility_date = "2023-02-28"
main = "./app/worker/index.ts"
name = "demo-cfw-ssr"
node_compat = true
workers_dev = true
[dev]
port = 3000
[[env.dev.kv_namespaces]]
binding = "DEMO_CFW_SSR"
id = "5dfd5a54a7174c83b56d5c55bd752c77"
preview_id = "5dfd5a54a7174c83b56d5c55bd752c77"
[[env.dev.kv_namespaces]]
binding = "DEMO_CFW_SSR_SESSIONS"
id = "a41123f53b804770b6808ef4b924f930"
preview_id = "a41123f53b804770b6808ef4b924f930"
[env.dev.vars]
AUTH0_DOMAIN = "shortpoet.auth0.com"
ENVIRONMENT = "dev"
LOG_LEVEL = "info"
[[env.prod.kv_namespaces]]
binding = "DEMO_CFW_SSR"
id = "5c6a1909d0844b4296607e021240e9f1"
preview_id = "5c6a1909d0844b4296607e021240e9f1"
[env.prod.vars]
ENVIRONMENT = "prod"
LOG_LEVEL = "error"
[site]
bucket = "./app/build/client"
