compatibility_date = "2022-05-03"
main = "./app/worker/index.ts"
name = "demo-cfw-ssr"
node_compat = true
workers_dev = true
[dev]
port = 3000
[env.dev]
ENVIRONMENT = "dev"
LOG_LEVEL = "debug"
[[env.dev.vars.kv_namespaces]]
binding = "DEMO_CFW_SSR"
id = "10d16e2123674b449ce69b3157b8ce09"
preview_id = "10d16e2123674b449ce69b3157b8ce09"
[env.prod]
ENVIRONMENT = "prod"
LOG_LEVEL = "error"
[[env.prod.vars.kv_namespaces]]
binding = "DEMO_CFW_SSR"
id = ""
preview_id = ""
[site]
bucket = "./app/build/client"
